#ifndef ROGUE_20177_GAME_PHASE
#define ROGUE_20177_GAME_PHASE

enum GamePhase
{
    PLAYERS_TURN,
    ENEMY_TURN,
    PLAYER_DEAD,
    TERMINAL_MENU,
    CONTAINER_MENU,
    CONTAINER_ITEM_MENU,
    INVENTORY_MENU,
    INVENTORY_ITEM_MENU,
    TARGETING_ITEM,
    TARGETING_SKILL,
    LEVEL_UP,
    CHARACTER_SCREEN,
    POPUP_MESSAGE,
    ENTITY_INFO,
    LEVEL_SUMMARY,
};


#endif /* ifndef ROGUE_20177_GAME_PHASE */
