#ifndef ROGUE_20177_GAME_PHASE
#define ROGUE_20177_GAME_PHASE

enum GamePhase
{
    PLAYERS_TURN,
    ENEMY_TURN,
    PLAYER_DEAD,
    INVENTORY_MENU,
    INVENTORY_ITEM_MENU,
    TARGETING,
    LEVEL_UP,
    CHARACTER_SCREEN,
    ENTITY_INFO,
};


#endif /* ifndef ROGUE_20177_GAME_PHASE */
